version: '3.8'

name: 'autohub365'

services:
  client:
    build:
      context: ../autohub365-app
      dockerfile: Dockerfile
    container_name: autohub365-client
    ports:
      - '5173:5173'
    environment:
      WATCHPACK_POLLING: true
    volumes:
      - ../autohub365-app:/app
      - /app/node_modules
    depends_on:
      - api

  api:
    build:
      context: ../autohub365-api
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    depends_on:
      - mongodb
      - postgres

  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=user
      - MONGODB_INITDB_ROOT_PASSWORD=pass
    ports:
      - '27017:27017'
    volumes:
      - mongodata:/data/db

  postgres:
    image: postgres:13.3
    environment:
      - POSTGRES_DB=autohub365
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/postgresql/data

volumes:
  mongodata:
  postgres-data:
