version: '3.8'

name: 'autohub365'

services:
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=user
      - MONGODB_INITDB_ROOT_PASSWORD=pass
    ports:
      - '27017:27017'
    volumes:
      - mongodata:/data/db

  postgres:
    image: postgres:13.3
    environment:
      - POSTGRES_DB=autohub365
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/postgresql/data

volumes:
  mongodata:
  postgres-data:
